version: "3"

services: 
  app:
    build: 
      context: .      
      args: 
        GO_VERSION: 1.17
        APP_NAME: app
        USERNAME=: user
        USER_UID: 1000
        USER_GID: 1000
        EXPOSE_PORTS: 3000
    container_name: app
